INSERT INTO ADDRESS(id, street, city, state, zip) VALUES (DEFAULT, 'Al. Szucha Jana Chrystiana 1038', 'Warszawa', 'Polska', '00-582');
INSERT INTO ADDRESS(id, street, city, state, zip) VALUES (DEFAULT, 'ul. Bracka 84', 'Tarnowskie Góry', 'Polska', '42-605');
INSERT INTO ADDRESS(id, street, city, state, zip) VALUES (DEFAULT, 'ul. Ratajczaka Franciszka 90', 'Szczecin', 'Polska', '61-816');
INSERT INTO ADDRESS(id, street, city, state, zip) VALUES (DEFAULT, 'ul. Projektowa 142', 'Katowice', 'Polska', '91-493');
INSERT INTO ADDRESS(id, street, city, state, zip) VALUES (DEFAULT, 'ul. Tymiankowa 57', 'Lublin', 'Polska', '20-221');
INSERT INTO ADDRESS(id, street, city, state, zip) VALUES (DEFAULT, 'ul. Zgierska 27', 'Łódź', 'Polska', '91-468');
INSERT INTO STUDENT(id, name, surname, age, address_id) VALUES (DEFAULT, 'Adam', 'Nowak', 18, 1);
INSERT INTO STUDENT(id, name, surname, age, address_id) VALUES (DEFAULT, 'Bartosz', 'Pawlak', 20, 2);
INSERT INTO STUDENT(id, name, surname, age, address_id) VALUES (DEFAULT, 'Kinga', 'Kowalczyk', 21, 3);
INSERT INTO STUDENT(id, name, surname, age, address_id) VALUES (DEFAULT, 'Wiktor', 'Kowalski', 20, 4);
INSERT INTO STUDENT(id, name, surname, age, address_id) VALUES (DEFAULT, 'Piotr', 'Szczepański', 22, 5);
INSERT INTO STUDENT(id, name, surname, age, address_id) VALUES (DEFAULT, 'Filip', 'Chmielewski', 19, 6);